# Generated by Django 3.1.1 on 2020-10-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='clearance',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
